refactor(ci): split the test workflow into separate files

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -147,6 +147,93 @@ jobs:
       run: mkdir -p ./ci-artifacts && mv ./ci-artifacts/downloaded-xtask/upsilon-xtask ./ci-artifacts/upsilon-xtask && chmod +x ./ci-artifacts/upsilon-xtask
     - name: Lint
       run: ./ci-artifacts/upsilon-xtask lint
+  test-linux:
+    name: Test (Linux)
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+    - name: Install lld
+      run: sudo apt-get install -y lld
+    - name: Install openssl
+      run: sudo apt-get install -y libssl-dev
+    - name: Install rust
+      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
+    - name: Install nextest
+      uses: taiki-e/install-action@nextest
+    - name: Print environment
+      run: "\n      env\n    "
+    - name: Collect other system information
+      run: "\n      git --version\n    "
+    - name: Compile xtask
+      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
+    - name: Compile binaries and tests
+      run: cargo xtask test --verbose --no-run --profile ci --custom-bin-dir ./bin-dir
+    - name: Run tests
+      run: cargo xtask test --verbose --no-fail-fast --profile ci --no-build-dev --custom-bin-dir ./bin-dir
+    - name: Run doctests
+      run: cargo xtask test --verbose --no-fail-fast --doc --profile ci --no-build-dev
+  test-linux-with-difftests:
+    name: Test (Linux with difftests)
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+    - name: Install lld
+      run: sudo apt-get install -y lld
+    - name: Install openssl
+      run: sudo apt-get install -y libssl-dev
+    - name: Install rust
+      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
+    - name: Install nextest
+      uses: taiki-e/install-action@nextest
+    - name: Print environment
+      run: "\n      env\n    "
+    - name: Collect other system information
+      run: "\n      git --version\n    "
+    - name: Compile xtask
+      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
+    - name: Compile binaries and tests (with difftests)
+      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
+    - name: Run tests (with difftests)
+      run: cargo xtask test --verbose --no-fail-fast --profile difftests --no-build-dev --custom-bin-dir ./bin-dir
+  test-linux-only-difftests:
+    name: Test (Linux only difftests)
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0
+    - name: Get old commit
+      id: get-old-commit
+      run: "\n    if [ \"$PUSH_BEFORE\" != \"\" ]; then\n        echo \"OLD_COMMIT=$PUSH_BEFORE\" >> $GITHUB_OUTPUT\n    else\n        if [ \"$PULL_REQUEST_BASE_SHA\" != \"\" ]; then\n            echo \"OLD_COMMIT=$PULL_REQUEST_BASE_SHA\" >> $GITHUB_OUTPUT\n        else\n            echo \"Error: neither PUSH_BEFORE nor PULL_REQUEST_BASE_SHA is set\" >&2\n            exit 1\n        fi\n    fi\n  "
+      env:
+        PUSH_BEFORE: ${{ github.event.before }}
+        PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
+    - name: Install lld
+      run: sudo apt-get install -y lld
+    - name: Install openssl
+      run: sudo apt-get install -y libssl-dev
+    - name: Install rust
+      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
+    - name: Install nextest
+      uses: taiki-e/install-action@nextest
+    - name: Print environment
+      run: "\n      env\n    "
+    - name: Collect other system information
+      run: "\n      git --version\n    "
+    - name: Compile xtask
+      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
+    - name: Compile binaries and tests (with difftests)
+      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
+    - name: Run tests (only difftests)
+      run: cargo xtask test-quick --from-index --verbose --no-fail-fast --profile difftests --algo git-diff-files --commit ${{ steps.get-old-commit.outputs.OLD_COMMIT }}
   compile-openssl-win:
     name: Compile openssl (Windows)
     runs-on: windows-latest
@@ -204,7 +291,7 @@ jobs:
       shell: pwsh
       run: 'ls env:'
     - name: Collect other system information
-      run: "\n          git --version\n        "
+      run: "\n      git --version\n    "
     - name: Compile xtask
       run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
     - name: Create xtask artifact dir
@@ -242,7 +329,7 @@ jobs:
       shell: pwsh
       run: 'ls env:'
     - name: Collect other system information
-      run: "\n          git --version\n        "
+      run: "\n      git --version\n    "
     - name: Download xtask
       uses: actions/download-artifact@v3
       with:
@@ -278,7 +365,7 @@ jobs:
       shell: pwsh
       run: 'ls env:'
     - name: Collect other system information
-      run: "\n          git --version\n        "
+      run: "\n      git --version\n    "
     - name: Download xtask
       uses: actions/download-artifact@v3
       with:
@@ -288,90 +375,3 @@ jobs:
       run: mv ./ci-artifacts/downloaded-xtask/upsilon-xtask.exe ./ci-artifacts/upsilon-xtask.exe
     - name: Run doctests
       run: ./ci-artifacts/upsilon-xtask.exe test --verbose --no-fail-fast --doc --profile ci --no-build-dev
-  test-linux:
-    name: Test (Linux)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-    - name: Install lld
-      run: sudo apt-get install -y lld
-    - name: Install openssl
-      run: sudo apt-get install -y libssl-dev
-    - name: Install rust
-      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
-    - name: Install nextest
-      uses: taiki-e/install-action@nextest
-    - name: Print environment
-      run: "\n          env\n        "
-    - name: Collect other system information
-      run: "\n          git --version\n        "
-    - name: Compile xtask
-      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
-    - name: Compile binaries and tests
-      run: cargo xtask test --verbose --no-run --profile ci --custom-bin-dir ./bin-dir
-    - name: Run tests
-      run: cargo xtask test --verbose --no-fail-fast --profile ci --no-build-dev --custom-bin-dir ./bin-dir
-    - name: Run doctests
-      run: cargo xtask test --verbose --no-fail-fast --doc --profile ci --no-build-dev
-  test-linux-with-difftests:
-    name: Test (Linux with difftests)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-    - name: Install lld
-      run: sudo apt-get install -y lld
-    - name: Install openssl
-      run: sudo apt-get install -y libssl-dev
-    - name: Install rust
-      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
-    - name: Install nextest
-      uses: taiki-e/install-action@nextest
-    - name: Print environment
-      run: "\n          env\n        "
-    - name: Collect other system information
-      run: "\n          git --version\n        "
-    - name: Compile xtask
-      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
-    - name: Compile binaries and tests (with difftests)
-      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
-    - name: Run tests (with difftests)
-      run: cargo xtask test --verbose --no-fail-fast --profile difftests --no-build-dev --custom-bin-dir ./bin-dir
-  test-linux-only-difftests:
-    name: Test (Linux only difftests)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-        fetch-depth: 0
-    - name: Get old commit
-      id: get-old-commit
-      run: "\n    if [ \"$PUSH_BEFORE\" != \"\" ]; then\n        echo \"OLD_COMMIT=$PUSH_BEFORE\" >> $GITHUB_OUTPUT\n    else\n        if [ \"$PULL_REQUEST_BASE_SHA\" != \"\" ]; then\n            echo \"OLD_COMMIT=$PULL_REQUEST_BASE_SHA\" >> $GITHUB_OUTPUT\n        else\n            echo \"Error: neither PUSH_BEFORE nor PULL_REQUEST_BASE_SHA is set\" >&2\n            exit 1\n        fi\n    fi\n  "
-      env:
-        PUSH_BEFORE: ${{ github.event.before }}
-        PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
-    - name: Install lld
-      run: sudo apt-get install -y lld
-    - name: Install openssl
-      run: sudo apt-get install -y libssl-dev
-    - name: Install rust
-      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
-    - name: Install nextest
-      uses: taiki-e/install-action@nextest
-    - name: Print environment
-      run: "\n          env\n        "
-    - name: Collect other system information
-      run: "\n          git --version\n        "
-    - name: Compile xtask
-      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
-    - name: Compile binaries and tests (with difftests)
-      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
-    - name: Run tests (only difftests)
-      run: cargo xtask test-quick --from-index --verbose --no-fail-fast --profile difftests --algo git-diff-files --commit ${{ steps.get-old-commit.outputs.OLD_COMMIT }}
